### ISSUE TITLE
No sé si quedan bien los tallymarks en blanco y negro dentro de la vizz en la ficha de cada partido

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#2]
Buscar solución.

**Comment by Saigesp** [comment]
Qué tal así

![Captura de pantalla de 2021-02-01 18-43-19](https://user-images.githubusercontent.com/3207982/106496672-76d1f580-64bd-11eb-80b4-172cf45ad43a.png)

**Comment by pr3ssh** [comment]
MOLA!
