### ISSUE TITLE
Orden de partidos en la HOME

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#20]
* Si no hay temática seleccionada: orden por cumplimiento general (media de _compliance_ de todas las temáticas de cada partido)
* Si hay temática seleccionada: orden por cumplimiento específico.

Poner 30 palitos como máximo, si hay temática seleccionada o no, y siempre priorizando los cumplimientos a los incumplimientos. Y luego poner ...

**Comment by Saigesp** [comment]
Closed with 85a6afc812e3f19dc05ca5940ad823de9a1339b5 and 86e501679ba50a331b19846afa5c9f012ed4c297
