### ISSUE TITLE
Qué hacer si no hay actos parlamentarios para un compromiso

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#22]
Poner **Sin actividad parlamentaria relevante** sin enlace

Ahora hay 3 bullets points por defecto y eso esta mal.

Ver si poner iconos en sin actividad parlamentaria y en el ver informe.

Lo hablamos si quieres.

**Comment by Saigesp** [comment]
Closed with 85a6afc812e3f19dc05ca5940ad823de9a1339b5
