### ISSUE TITLE
Contenido de las páginas estáticas

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#24]
https://docs.google.com/document/d/1xEoGWJ_0tO_YMHZ04Qfo32pt39UW7k22WsK2aTeO-dU/edit?usp=sharing

Aqui están las de Acerca, Metodología, Contacto y una nueva llamada Informe COVID que debería tener subapartados en la misma página que se expandan/colapsen.

**Comment by Saigesp** [comment]
Closed with 7d4324b9807174d07e02305a83c730d3e1b3b871

**Comment by pr3ssh** [comment]
@Saigesp Se pasó esto: _una nueva página llamada Informe COVID que debería tener subapartados en la misma página que se expandan/colapsen_

**Comment by Saigesp** [comment]
Está enlazada en el footer:
![Captura de pantalla de 2021-02-05 15-25-26](https://user-images.githubusercontent.com/3207982/107046023-793a9500-67c6-11eb-9cb3-5906c3feba92.png)

No he puesto los subapartados desplegables porque en mi opinión no es un contenido secundario y (en mi humilde opinión) no deberían estar escondidos. No obstante no me cuesta nada hacerlo si lo queréis
