### ISSUE TITLE
En la HOME no hay palitos naranjas

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#26]
Con un máximo de palitos previsto, el orden debería ser: verdes, naranjas y rojos, sin superar el máximo.

**Comment by Saigesp** [comment]
Esto creo que no nos hemos entendido bien, detallo como funciona la Home:

- Cuando hay una temática seleccionada, los partidos se ordenan en función del score de esa temática (utiliza los valores de `party.overview`) y muestra palitos en función del número de compromisos cumplidos/parciales/incumplidos.
- Cuando no hay ninguna temática seleccionada, los partidos se ordenan haciendo una media de todos sus scores (`party.overview`) y muestra los palitos **en función de estos scores**: si el partido tiene una media de 3.7 mostrará 4 palitos verdes y 6 rojos

**Comment by pr3ssh** [comment]
* Ok
* Esto no está demasiado claro porque puede tener palitos naranjas y con este modelo nunca se mostrarían.
