### ISSUE TITLE
Ficha PARTIDO: Buscar solución para que en los móviles se sepa que hay más tabs porque a veces solo se muestran dos

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#31]

**Comment by Saigesp** [comment]
He hecho una pequeña animación al cargar la página de partido, para que se vea que el menu es scrolleable horizontalmente. Creo que queda bien, pero revísalo please y vemos si tocar los ajustes (tiempos, velocidad)

**Comment by pr3ssh** [comment]
Me encanta!!! Solo lo pondría un poco más lenta para que se perciba mejor.
