### ISSUE TITLE
Ficha de PARTIDO: Al querer salir de dicha vista hacia la HOME la página se pone negra y ahi se queda

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#32]

**Comment by pr3ssh** [comment]
Solo desde algunos partidos (Ciudadanos, BNG) pero desde Gobierno no.

**Comment by Saigesp** [comment]
El problema es la key `compliance` de cada iniciativa. Estaban soportados 3 valores (caseinsensitive): CUMPLIDO, NO CUMPLIDO, PARCIALMENTE CUMPLIDO.

En la iniciativa de Ciudadanos `Adaptaremos nuestra normativa laboral a las nuevas realidades` hay un `"compliance": "PARCIALMENTE CUMPLIDO/ NO CUMPLIDO"` que es lo que producía el error. He corregido la lógica para que no pete, y queda de la siguiente forma:

```
if (compliance === 'CUMPLIDO') {
  CUMPLIDO += 1;
} else if (compliance === 'PARCIALMENTE CUMPLIDO') {
  PARCIALMENTE_CUMPLIDO += 1;
} else {
  NO_CUMPLIDO += 1;
}
```

**Comment by pr3ssh** [comment]
Creo que podremos corregirlo en los datos porque es algo anómalo pero muy bueno ese _hack_ para que no pete.
