### ISSUE TITLE
Al entrar en la ficha de un PARTIDO hay problemas a veces con los refrescos de las gráficas

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#33]

**Comment by Saigesp** [comment]
@pr3ssh puedes especificarme qué partido? Que estoy buscando y no doy con la tecla

**Comment by pr3ssh** [comment]
@Saigesp Entra por ej en BNG y la gráfica de Cambio climático aparece sin actualizar.

**Comment by Saigesp** [comment]
Ok, perfecto, ya lo he visto
