### ISSUE TITLE
Las paginas de partido no son accesibles directamente

### ISSUE THREAD

**Issue by DavidHernandez** [politicalwatch/ojito#36]
Al acceder a la pagina de un partido directamente, la aplicacion da un error 404. Por ejemplo:

https://ojito.politicalwatch.es/partido/Ciudadanos

![Screenshot from 2021-02-08 12-19-46](https://user-images.githubusercontent.com/877002/107212968-06b8f780-6a08-11eb-9f64-a0400e223642.png)

Si accedes desde la homepage si que funciona:

![Screenshot from 2021-02-08 12-19-35](https://user-images.githubusercontent.com/877002/107212980-0ae51500-6a08-11eb-8dd0-2fa50a4aaa0b.png)

Esto impide que se puedan enlazar las diferentes paginas.

**Comment by Saigesp** [comment]
@DavidHernandez  Arreglado. Las rutas cambian a https://ojito.politicalwatch.es/#/partido/Gobierno (atención al #) pero ya se puede acceder directamente
