### ISSUE TITLE
Enlaces a iniciativas rotos

### ISSUE THREAD

**Issue by DavidHernandez** [politicalwatch/ojito#37]
Hay algunos enlaces a iniciativas que están rotos. Por ejemplo en la sección de Infancia Migrante del Gobierno, el enlace a la iniciativa da un error: https://ojito.politicalwatch.es/#/partido/Gobierno

@pr3ssh no tengo claro si esto es un problema de contenido nuestro o una issue en el lado del código.

**Comment by pr3ssh** [comment]
Es nuestro. Lo corrijo.
