### ISSUE TITLE
En el footer de la HOME meter el logo de Political Watch

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/ojito#4]
![PW_PRINCIPAL_DATOS_NEGATIVO_02](https://user-images.githubusercontent.com/404339/106012543-d09c7f00-60bb-11eb-83e5-7e47a4509c49.png)

**Comment by Saigesp** [comment]
Done in f259223c84b3d45c0bc25e612aee8dba4c9e865c (sorry I put the wrong number)
